import json
import re

# 1. 100 REAL FLAGSHIP PHONES
phones = [
  ("iPhone 15 Pro Max", "$1,199", "Apple A17 Pro (3nm TSMC)", "48MP Main + 12MP 5x Periscope + 12MP Ultra-Wide", "4,422 mAh (29h Video)", "8GB LPDDR5", "256GB / 1TB NVMe", "United States", "https://www.apple.com/iphone-15-pro/", "Flagship Apple smartphone crafted from Grade 5 aerospace titanium with hardware ray-tracing and customizable Action button."),
  ("Samsung Galaxy S24 Ultra", "$1,299", "Snapdragon 8 Gen 3 for Galaxy", "200MP Main + 50MP 5x Periscope + 10MP 3x + 12MP Ultra-Wide", "5,000 mAh (45W Fast)", "12GB LPDDR5X", "512GB / 1TB UFS 4.0", "South Korea", "https://www.samsung.com/galaxy-s24-ultra/", "Titanium powerhouse with integrated S-Pen stylus, flat 2,600-nit AMOLED display, and on-device Galaxy AI translation."),
  ("Google Pixel 8 Pro", "$999", "Google Tensor G3 + Titan M2", "50MP Octa-PD + 48MP 5x Quad-PD + 48MP Ultra-Wide", "5,050 mAh (30W Fast)", "12GB LPDDR5X", "512GB UFS 4.0", "United States", "https://store.google.com/product/pixel_8_pro", "Google computational AI flagship with Magic Eraser, Best Take, on-device Gemini Nano, and 7 years of full Android OS updates."),
  ("Xiaomi 14 Ultra", "$1,499", "Snapdragon 8 Gen 3", "Leica Quad 50MP (1-inch Sony LYT-900 stepless variable aperture)", "5,000 mAh (90W Wired / 80W Wireless)", "16GB LPDDR5X", "512GB / 1TB UFS 4.0", "China", "https://www.mi.com/global/product/xiaomi-14-ultra/", "Photography masterpiece co-engineered with Leica, utilizing the 1-inch LYT-900 sensor and stepless variable mechanical aperture."),
  ("OnePlus 12", "$799", "Snapdragon 8 Gen 3", "Hasselblad 50MP LYT-808 + 64MP 3x Periscope + 48MP Ultra-Wide", "5,400 mAh (100W SuperVOOC)", "16GB / 24GB LPDDR5X", "512GB UFS 4.0", "China", "https://www.oneplus.com/12", "Value performance flagship featuring a 4,500 nit 2K ProXDR 120Hz display and 100W SuperVOOC flash charging."),
  ("Vivo X100 Pro", "$899", "MediaTek Dimensity 9300", "Zeiss APO 50MP 1-inch IMX989 + 50MP Floating Periscope", "5,400 mAh BlueOcean (100W Fast)", "16GB LPDDR5X", "512GB UFS 4.0", "China", "https://www.vivo.com/en/products/x100pro", "Camera benchmark with certified Zeiss APO telephoto lens, V3 imaging chip, and sunburst stainless steel camera housing."),
  ("Sony Xperia 1 VI", "$1,399", "Snapdragon 8 Gen 3", "Exmor T 48MP 24mm + 85-170mm True Optical Continuous Zoom Telephoto", "5,000 mAh (2-Day Life)", "12GB LPDDR5X", "512GB UFS 4.0", "Japan", "https://www.sony.com/electronics/smartphones/xperia-1m6", "Creator smartphone with continuous mechanical optical zoom between 85mm and 170mm, 3.5mm headphone jack, and Alpha autofocus."),
  ("Asus ROG Phone 8 Pro", "$1,199", "Snapdragon 8 Gen 3 (Overclocked)", "50MP Sony IMX890 Gimbal OIS + 32MP 3x Telephoto", "5,500 mAh Dual-Cell (65W HyperCharge)", "24GB LPDDR5X", "1TB UFS 4.0", "Taiwan", "https://rog.asus.com/phones/rog-phone-8-pro/", "Ultimate gaming powerhouse with 165Hz Samsung AMOLED, rear AniMe Matrix Mini-LED customization, and AirTrigger ultrasonic controls."),
  ("Honor Magic6 Pro", "$1,099", "Snapdragon 8 Gen 3", "180MP Periscope Telephoto + 50MP Falcon H9000", "5,600 mAh Silicon-Carbon Battery", "16GB LPDDR5X", "512GB UFS 4.0", "China", "https://www.honor.com/global/phones/honor-magic6-pro/", "Introduced 2nd Gen Silicon-Carbon battery for extreme sub-zero endurance paired with a 180MP periscope zoom sensor."),
  ("Huawei Pura 70 Ultra", "$1,499", "HiSilicon Kirin 9010 (7nm)", "Pop-Up Retractable 1-inch 50MP + 50MP Macro Telephoto", "5,200 mAh (100W SuperCharge)", "16GB LPDDR5X", "512GB / 1TB UFS 4.0", "China", "https://consumer.huawei.com/en/phones/pura70-ultra/", "Motorized retractable 1-inch camera module with mechanical sound and Ultra Speed Snapshot up to 300 km/h."),
  ("Samsung Galaxy Z Fold5", "$1,799", "Snapdragon 8 Gen 2 for Galaxy", "50MP Dual Pixel OIS + 10MP 3x + 12MP Ultra-Wide", "4,400 mAh (25W Fast)", "12GB LPDDR5X", "512GB / 1TB UFS 4.0", "South Korea", "https://www.samsung.com/galaxy-z-fold5/", "Pioneering book-style foldable with zero-gap Flex Hinge, water resistance, and desktop-class multitasking."),
  ("Google Pixel Fold", "$1,799", "Google Tensor G2 + Titan M2", "48MP Quad PD + 10.8MP 5x + 10.8MP Ultra-Wide", "4,821 mAh (30W Fast)", "12GB LPDDR5", "256GB / 512GB", "United States", "https://store.google.com/product/pixel_fold", "Thin foldable with wide passport aspect ratio outer display and seamless Google workspace split-screen."),
  ("OnePlus Open", "$1,499", "Snapdragon 8 Gen 2", "Hasselblad 48MP LYT-T808 + 64MP 3x Periscope + 48MP Ultra-Wide", "4,805 mAh (67W SuperVOOC)", "16GB LPDDR5X", "512GB UFS 4.0", "China", "https://www.oneplus.com/open", "Celebrated as the lightest foldable flagship with Open Canvas triple multi-tasking and anti-reflective 2K screens."),
  ("Vivo X Fold3 Pro", "$1,599", "Snapdragon 8 Gen 3", "Zeiss 50MP OV50H + 64MP 3x Periscope + 50MP Ultra-Wide", "5,700 mAh Silicon-Anode (100W Fast)", "16GB LPDDR5X", "1TB UFS 4.0", "China", "https://www.vivo.com", "World thinnest and lightest Snapdragon 8 Gen 3 foldable featuring armor glass and dual ultrasonic fingerprint scanners."),
  ("Motorola Razr 40 Ultra", "$999", "Snapdragon 8+ Gen 1", "12MP Dual Pixel OIS + 13MP Ultra-Wide Macro", "3,800 mAh (30W TurboPower)", "8GB / 12GB LPDDR5", "256GB / 512GB", "United States", "https://www.motorola.com", "Iconic clamshell flippable smartphone with a massive 3.6-inch 144Hz external cover screen that runs any Android app."),
  ("Samsung Galaxy Z Flip5", "$999", "Snapdragon 8 Gen 2 for Galaxy", "12MP Dual Pixel + 12MP Ultra-Wide", "3,700 mAh (25W Fast)", "8GB LPDDR5X", "256GB / 512GB", "South Korea", "https://www.samsung.com/galaxy-z-flip5/", "Compact pocketable foldable with 3.4-inch Flex Window for widget control and hands-free selfie capture."),
  ("Xiaomi Mix Fold 3", "$1,399", "Snapdragon 8 Gen 2 Leading Version", "Leica Quad 50MP with Dual Telephoto", "4,800 mAh (67W Fast)", "16GB LPDDR5X", "512GB / 1TB", "China", "https://www.mi.com", "Ultra-slim foldable with custom micro waterdrop hinge, carbon-fiber plate, and comprehensive Leica optical filters."),
  ("Nothing Phone (2)", "$599", "Snapdragon 8+ Gen 1", "50MP Sony IMX890 OIS + 50MP Samsung JN1", "4,700 mAh (45W Fast)", "12GB LPDDR5", "256GB / 512GB", "United Kingdom", "https://nothing.tech", "London-designed transparent casing with customizable Glyph Interface LED lighting and minimalist Nothing OS."),
  ("Sony Xperia 5 V", "$899", "Snapdragon 8 Gen 2", "Exmor T 48MP + 12MP Ultra-Wide", "5,000 mAh (30W Fast)", "8GB LPDDR5X", "128GB / 256GB", "Japan", "https://www.sony.com", "Compact premium powerhouse with front-facing stereo speakers, high-resolution audio DAC, and 120Hz OLED."),
  ("Asus Zenfone 11 Ultra", "$899", "Snapdragon 8 Gen 3", "50MP Sony IMX890 6-Axis Gimbal OIS + 32MP 3x", "5,500 mAh (65W HyperCharge)", "16GB LPDDR5X", "512GB UFS 4.0", "Taiwan", "https://www.asus.com", "Large-screen flagship with 6-axis hybrid gimbal stabilization 3.0 and on-device AI noise cancelation."),
  ("Realme GT 5 Pro", "$599", "Snapdragon 8 Gen 3", "50MP Sony LYT-808 + 50MP Sony IMX890 3x Periscope", "5,400 mAh (100W SuperVOOC)", "16GB LPDDR5X", "512GB / 1TB", "China", "https://www.realme.com", "Flagship killer featuring a 4,500-nit BOE display, massive vapor chamber cooling, and Palm Unlock bio-sensing."),
  ("Meizu 21 Pro", "$799", "Snapdragon 8 Gen 3", "50MP OV50H Main + 13MP Ultra-Wide + 10MP 3x Telephoto", "5,050 mAh (80W Wired / 50W Wireless)", "16GB LPDDR5X", "512GB / 1TB", "China", "https://www.meizu.com", "Flyme Auto ecosystem flagship with symmetrical white bezel aesthetics and mEngine Ultra large linear haptics."),
  ("Nubia RedMagic 9 Pro+", "$999", "Snapdragon 8 Gen 3 (22,000 RPM RGB Fan)", "50MP Samsung GN5 OIS + 50MP JN1 (Flush Back)", "5,500 mAh Dual-Cell (165W Magic Charge)", "24GB LPDDR5X", "1TB UFS 4.0", "China", "https://redmagic.gg", "Zero-camera-bump completely flat glass back with true under-display selfie camera and 520Hz shoulder gaming triggers."),
  ("Oppo Find N3", "$1,699", "Snapdragon 8 Gen 2", "Hasselblad 48MP LYT-T808 + 64MP 3x Periscope", "4,805 mAh (67W SuperVOOC)", "16GB LPDDR5X", "512GB UFS 4.0", "China", "https://www.oppo.com", "Luxury foldable featuring dedicated hardware security island chip and boundary-free multi-window Canvas."),
  ("Honor Magic V2", "$1,599", "Snapdragon 8 Gen 2", "50MP Main OIS + 20MP 2.5x Telephoto + 50MP Ultra-Wide", "5,000 mAh Silicon-Carbon (66W Fast)", "16GB LPDDR5X", "512GB", "China", "https://www.honor.com", "Broke world record as thinnest inward foldable at 9.9mm folded thickness with titanium alloy hinge mechanism."),
  ("ZTE Axon 60 Ultra", "$899", "Snapdragon 8 Gen 2", "50MP Sony IMX787 OIS + 50MP Ultra-Wide + 50MP Telephoto", "6,000 mAh Silicon-Carbon (80W Wired)", "16GB LPDDR5X", "512GB", "China", "https://www.ztedevices.com", "Security flagship with dual OS architecture, direct satellite voice and SMS telemetry, and military-grade encryption."),
  ("Fairphone 5", "$699", "Qualcomm QCM6490 (Industrial)", "50MP Sony IMX800 OIS + 50MP Ultra-Wide", "4,200 mAh Removable (30W Fast)", "8GB LPDDR4X", "256GB + MicroSD 2TB", "Netherlands", "https://www.fairphone.com", "Most sustainable smartphone in history with 100% modular user-repairable parts and 10-year software roadmap."),
  ("Poco F6 Pro", "$499", "Snapdragon 8 Gen 2", "50MP Light Fusion 800 OIS + 8MP Ultra-Wide", "5,000 mAh (120W HyperCharge)", "12GB / 16GB LPDDR5X", "512GB / 1TB", "China", "https://www.po.co", "Performance bargain with WQHD+ 120Hz Flow AMOLED display, 120W charging from 0 to 100% in 19 minutes."),
  ("Redmi K70 Pro", "$549", "Snapdragon 8 Gen 3", "50MP Light Hunter 800 OIS + 50MP 2x Portrait + 12MP Ultra-Wide", "5,000 mAh (120W Wired)", "16GB / 24GB LPDDR5X", "512GB / 1TB", "China", "https://www.mi.com", "Xiaomi sub-brand powerhouse with 4,000 nit 2K OLED panel, metallic frame, and Surge P2 charging management chip."),
  ("Honor 200 Pro", "$699", "Snapdragon 8s Gen 3", "50MP H9000 OIS + 50MP Sony IMX856 2.5x + 12MP Ultra-Wide", "5,200 mAh Silicon-Carbon (100W / 66W)", "12GB / 16GB LPDDR5X", "512GB", "China", "https://www.honor.com", "Studio portrait specialist developed in collaboration with Studio Harcourt Paris for authentic cinematic studio lighting."),
  ("Infinix GT 20 Pro", "$329", "MediaTek Dimensity 8200 Ultimate", "108MP OIS + 2MP Macro", "5,000 mAh (45W)", "12GB LPDDR5X", "256GB UFS 3.1", "China", "https://infinixmobility.com", "Cyber mecha aesthetic gaming phone with dedicated display pixelworks gaming chip and 144Hz bezel-less screen."),
  ("Tecno Phantom V Fold", "$1,099", "Dimensity 9000+", "50MP Main + 50MP 2x Telephoto + 13MP Ultra-Wide", "5,000 mAh (45W)", "12GB LPDDR5X", "512GB UFS 3.1", "China", "https://tecno-mobile.com", "Value flagship book-style foldable bringing dual 120Hz AMOLED screens and 50MP portrait sensors to accessible tiers."),
  ("Sharp Aquos R8 Pro", "$1,299", "Snapdragon 8 Gen 2", "Leica 47.2MP 1-inch Sensor with 14-channel Spectrum", "5,000 mAh", "12GB LPDDR5X", "256GB UFS 4.0", "Japan", "https://jp.sharp", "Japanese imaging master with 1-inch image sensor, IGZO OLED 240Hz variable display, and aluminum heat sink ring."),
  ("Black Shark 5 Pro", "$799", "Snapdragon 8 Gen 1", "108MP Samsung S5KHM2 + 13MP Ultra-Wide", "4,650 mAh (120W)", "16GB LPDDR5", "512GB UFS 3.1", "China", "https://blackshark.com", "Mechanical pop-up magnetic gaming triggers with dual sandwich liquid cooling and DXOMARK audio top score."),
  ("Doogee V30T 5G", "$399", "MediaTek Dimensity 1080", "108MP Main + 20MP Night Vision + 16MP Wide", "10,800 mAh (66W)", "12GB LPDDR4X", "256GB UFS 2.2", "China", "https://doogee.cc", "Ultra-rugged outdoor flagship with built-in Sony night vision infrared camera, ceramic finish, and 10,800 mAh endurance."),
  ("Ulefone Armor 24", "$449", "MediaTek Helio G96", "64MP Main + 64MP Night Vision", "22,000 mAh (66W)", "12GB LPDDR4X", "256GB UFS 2.1", "China", "https://ulefone.com", "Mega-endurance rugged beast with massive 22,000 mAh battery pack, 1,000 lumen camping LED light, and uSmart connector."),
  ("Unihertz Tank 3 Pro", "$599", "Dimensity 8200 5G", "200MP Main + 64MP Night Vision + 50MP Telephoto", "23,800 mAh (120W)", "16GB / 18GB LPDDR5", "512GB UFS 3.1", "China", "https://unihertz.com", "Heavy-duty field explorer packing built-in 120Hz DLP laser projector, rangefinder, and dual camping floodlights."),
  ("HTC U24 Pro", "$599", "Snapdragon 7 Gen 3", "50MP OIS + 50MP 2x Telephoto + 8MP Ultra-Wide", "4,600 mAh (60W / 15W Qi)", "12GB LPDDR5", "256GB / 512GB", "Taiwan", "https://www.htc.com", "HTC return flagship integrated with Viverse virtual reality companion, 3.5mm jack, micro-SD slot, and IP68."),
  ("Kyocera DuraForce Pro 3", "$899", "Snapdragon 7 Gen 1", "64MP Main + 16MP Ultra-Wide + 2MP Macro", "4,270 mAh Swappable", "6GB LPDDR4X", "128GB + MicroSD", "Japan", "https://kyoceramobile.com", "Mil-STD-810H and non-incendive Class I Div 2 hazardous location certified rugged enterprise phone with hot-swappable battery."),
  ("Cat S75 Satellite", "$599", "MediaTek Dimensity 930", "50MP Main + 8MP Wide + 2MP Macro", "5,000 mAh", "6GB LPDDR4X", "128GB + MicroSD", "United Kingdom", "https://catphones.com", "Direct-to-satellite messaging and SOS distress locator with drop-proof steel reinforced frame and bleach washable body."),
  ("Sonim XP10 5G", "$899", "Snapdragon 480+ 5G", "50MP Main + 8MP Wide", "5,000 mAh Removable", "6GB LPDDR4X", "128GB", "United States", "https://sonimtech.com", "Ultra-rugged mission-critical Push-To-Talk handset engineered for first responders, oil rigs, and extreme cold."),
  ("Gigaset GX6 Pro", "$629", "MediaTek Dimensity 900", "50MP OIS + 2MP Macro", "5,000 mAh Removable (30W)", "8GB LPDDR4X", "128GB", "Germany", "https://www.gigaset.com", "Made in Germany rugged business smartphone featuring replaceable battery, dual-SIM, programmable function key, and 5G."),
  ("Crosscall Core-Z5", "$799", "Qualcomm QCM6490", "48MP Main", "4,950 mAh", "4GB / 6GB LPDDR4X", "64GB / 128GB", "France", "https://crosscall.com", "French designed PMR mission-critical communication device with 100dB speaker, glove-touch 120Hz display, and 5-year warranty."),
  ("Oukitel WP30 Pro", "$599", "Dimensity 8050 5G", "108MP Samsung + 20MP Night Vision", "11,000 mAh (120W Charge)", "12GB LPDDR4X", "512GB UFS 3.1", "China", "https://oukitel.com", "World fastest-charging rugged flagship filling 11,000 mAh to 50% in 15 minutes with rear 1.8-inch AMOLED status screen."),
  ("Blackview BL9000 Pro", "$549", "Dimensity 8020 5G", "50MP OIS + FLIR Lepton 3.5 Thermal", "8,800 mAh (120W)", "12GB LPDDR4X", "512GB UFS 3.1", "China", "https://blackview.hk", "Integrated FLIR thermal imaging camera detecting heat leaks, electrical overloads, and pipe blockages up to 400°C.")
]

# Expand phones to 100
phone_extras = [
  ("Cubot KingKong 9", "$299", "Helio G99 6nm", "100MP Main + 24MP Night Vision", "10,600 mAh (33W)", "12GB", "256GB", "China", "https://cubot.net", "Dual-screen rugged device with rear 1.32-inch touchscreen and 100MP clarity sensor."),
  ("Fossibot F102", "$259", "Helio G99 6nm", "108MP Main + 20MP Night Vision", "16,500 mAh (33W)", "12GB", "256GB", "China", "https://fossibot.com", "Camping survival phone with massive 3W 495-lumen ultra-bright camp light."),
  ("UMIDIGI Bison GT2 Pro", "$349", "Dimensity 900 5G", "64MP Main + 8MP Wide + 5MP Macro", "6,150 mAh", "8GB", "256GB", "China", "https://umidigi.com", "Industrial AG matte fiberglass and rubber bumper casing with headset-free FM radio."),
  ("Hotwav Cyber 13 Pro", "$229", "Unisoc T619", "64MP Main + 8MP Wide", "10,800 mAh", "12GB", "256GB", "China", "https://hotwav.com", "150-lumen emergency flashlight with IP68 and IP69K high pressure water jet rating."),
  ("IIIF150 B2 Pro", "$289", "Helio G99 6nm", "108MP Main + 24MP Night Vision", "10,000 mAh (30W)", "12GB", "256GB", "China", "https://iiif150.com", "Ultra-thin rugged smartphone at just 14.9mm thickness with underwater camera mode."),
  ("Doogee S110", "$329", "Helio G99 6nm", "50MP Sony IMX766 + 24MP Night Vision", "10,800 mAh (66W)", "12GB", "256GB", "China", "https://doogee.cc", "Aerospace mecha back panel styling with smart interactive rear dial display."),
  ("Ulefone Power Armor 18T Ultra", "$599", "Dimensity 7050 5G", "108MP Main + FLIR Thermal Lepton 3.5", "9,600 mAh (66W)", "12GB", "512GB", "China", "https://ulefone.com", "Comprehensive industrial diagnostics tool combining 5G speed with FLIR thermal inspection."),
  ("Blackview BV9300", "$319", "Helio G99 6nm", "50MP Main + 8MP Wide + Laser Rangefinder", "15,080 mAh (33W)", "12GB", "256GB", "China", "https://blackview.hk", "Integrated 40m laser rangefinder with millimeter accuracy for architecture and interior measurements."),
  ("Oukitel WP21 Ultra", "$389", "Helio G99 6nm", "64MP Main + 20MP Night Vision + InfiRay Thermal", "9,800 mAh (66W)", "12GB", "256GB", "China", "https://oukitel.com", "256x192 InfiRay industrial thermal detector with 25Hz smooth refresh rate."),
  ("Cubot Quest", "$199", "Helio P22", "12MP Sony + 2MP Depth", "4,000 mAh", "4GB", "64GB", "China", "https://cubot.net", "Super-slim sports rugged phone engineered specifically for cycling and mountain trail runners."),
  ("AGM Glory Pro 5G", "$699", "Snapdragon 480 5G", "48MP Main + 20MP Night Vision + Thermal", "6,200 mAh Sub-Zero Battery", "8GB", "256GB", "Germany", "https://agmmobile.com", "Arctic battery technology guaranteed to operate continuously in -40°C sub-zero environments."),
  ("Sonim XP8", "$699", "Snapdragon 630", "12MP Main", "4,900 mAh Removable", "4GB", "64GB", "United States", "https://sonimtech.com", "Intrinsically safe certified ultra-rugged tool designed for extreme chemical refinery hazardous zones."),
  ("Cat S62 Pro", "$499", "Snapdragon 660", "12MP Dual Pixel + FLIR Thermal MSX", "4,000 mAh", "6GB", "128GB", "United Kingdom", "https://catphones.com", "Professional-grade thermal imaging tool powered by the highest resolution FLIR Lepton sensor."),
  ("Kyocera Brigadier", "$399", "Snapdragon 400", "8MP Main", "3,100 mAh (Qi Wireless)", "2GB", "16GB", "Japan", "https://kyoceramobile.com", "Pioneered pure Sapphire Shield scratch-proof front crystal screen that resists rock strikes."),
  ("Unihertz Titan Pocket", "$299", "Helio P70", "16MP Main", "4,000 mAh", "6GB", "128GB", "China", "https://unihertz.com", "Compact physical QWERTY keyboard smartphone designed for distraction-free typing and productivity."),
  ("Punkt MP02 4G", "$379", "Snapdragon 210", "Minimalist Monochrome Display", "1,280 mAh (7-Day Standby)", "2GB", "16GB", "Switzerland", "https://punkt.ch", "Swiss-designed voice phone featuring BlackBerry secure cryptographic architecture and Signal integration."),
  ("Light Phone II", "$299", "Qualcomm MSM8909W", "Black & White E-Ink Matte Screen", "950 mAh", "1GB", "8GB", "United States", "https://thelightphone.com", "Digital detox minimalist handset engineered to be used as little as possible with no internet feed."),
  ("Mudita Pure", "$369", "ARM Cortex-M7 Ultra Low Power", "2.84-inch E-Ink Display (Ultra Low SAR)", "1,600 mAh", "64MB", "16GB", "Poland", "https://mudita.com", "Health-conscious acoustic phone with ultra-low radiation SAR antenna and custom MuditaOS."),
  ("Minimal Phone", "$400", "MediaTek MT6769", "E-Paper Screen + Tactile QWERTY Keyboard", "4,000 mAh", "4GB", "128GB", "United States", "https://tryminimal.com", "E-paper productivity device with backlit physical tactile QWERTY keyboard and 4-day battery life."),
  ("Boox Palma", "$279", "Qualcomm Octa-Core", "16MP Document Scanner", "3,950 mAh", "6GB", "128GB + MicroSD", "China", "https://boox.com", "Pocket e-reader smartphone format with Carta 1200 E-Ink paper screen and dual-tone front lights."),
  ("Hisense A9 Pro", "$369", "Snapdragon 662", "13MP Main", "4,000 mAh", "8GB", "256GB", "China", "https://hisense.com", "Dedicated 300 PPI black and white e-ink reading phone with high fidelity ES9318 audio DAC chip."),
  ("TCL NXTPAPER 40", "$249", "Helio G88", "50MP Main + 5MP Wide + 2MP Macro", "5,010 mAh (33W)", "8GB", "256GB", "China", "https://tcl.com", "Paper-like anti-glare matte display with zero blue light emission and color paper reading modes."),
  ("BlackBerry KEY2 LE", "$399", "Snapdragon 636", "13MP + 5MP Dual Rear", "3,000 mAh", "4GB", "64GB", "Canada", "https://blackberry.com", "Physical tactile keyboard with Speed Key shortcut switcher and DTEK real-time security telemetry."),
  ("HTC Exodus 1", "$699", "Snapdragon 845", "16MP + 12MP Dual Main", "3,500 mAh", "6GB", "128GB", "Taiwan", "https://htc.com", "Cryptocurrency hardware wallet smartphone with secure enclave Zion vault completely isolated from Android OS."),
  ("Sirin Solarin", "$14,000", "Snapdragon 810", "23.8MP Laser Autofocus", "4,000 mAh", "4GB", "128GB", "Switzerland", "https://sirinlabs.com", "Military-grade ultra-luxury security device featuring physical cyber switch initiating 256-bit encrypted phone calls."),
  ("Turing Phone Cadenza", "$1,299", "Snapdragon 820", "20MP Main", "3,000 mAh", "3GB", "64GB", "United States", "https://turingphone.com", "Chassis forged from Liquidmorphium liquid metal alloy stronger than titanium and steel."),
  ("Essential Phone PH-1", "$499", "Snapdragon 835", "13MP Dual RGB + Mono", "3,040 mAh", "4GB", "128GB", "United States", "https://essential.com", "Andy Rubin titanium and ceramic masterpiece introducing the worlds first edge-to-edge camera cutout."),
  ("Nextbit Robin", "$299", "Snapdragon 808", "13MP Phase Detection", "2,680 mAh", "3GB", "32GB Cloud-Integrated", "United States", "https://nextbit.com", "Cloud-first smartphone with mint colorway and automated cloud offloading of idle apps."),
  ("YotaPhone 2", "$599", "Snapdragon 800", "8MP Main", "2,500 mAh", "2GB", "32GB", "Russia", "https://yotaphone.com", "Pioneering dual-screen phone featuring front color AMOLED and rear full-touch electronic paper display."),
  ("Saygus V2", "$599", "Snapdragon 801", "21MP OIS + 13MP OIS Front", "3,100 mAh Swappable", "3GB", "64GB Dual MicroSD", "United States", "https://saygus.com", "Power user handset with dual microSD slots supporting 1TB storage, waterproof body, and 60GHz wireless gaming."),
  ("Lumigon T3", "$925", "Helio X10", "13MP 4K + 4MP Night Vision", "2,280 mAh (Wireless)", "3GB", "128GB", "Denmark", "https://lumigon.com", "Danish luxury design with marine-grade 316L stainless steel and 24-karat gold plating editions."),
  ("Vertu Signature Touch", "$9,000", "Snapdragon 810", "21MP Hasselblad Certified", "3,160 mAh (Qi Fast)", "4GB", "64GB", "United Kingdom", "https://vertu.com", "Handcrafted in England with Grade 5 titanium, English calf leather, and sapphire crystal glass front."),
  ("Tonino Lamborghini 88 Tauri", "$6,000", "Snapdragon 801", "20MP Main", "3,400 mAh", "3GB", "64GB", "Italy", "https://lamborghini.it", "Italian luxury mobile wrapped in hand-stitched leather and gold stainless steel chassis."),
  ("Gresso Regal Gold", "$6,000", "Quad-Core 1.5GHz", "13MP Main", "2,600 mAh", "2GB", "32GB", "Switzerland", "https://gresso.com", "Titanium luxury phone coated with PVD titanium and 18-karat yellow gold inset plate."),
  ("Caviar Cyberphone", "$7,500", "Apple A13 Bionic Custom", "12MP Triple OIS", "3,969 mAh", "4GB", "512GB", "Russia", "https://caviar.global", "Custom titanium origami folding protective cover inspired by the angular lines of Tesla Cybertruck."),
  ("Porsche Design Huawei Mate 40 RS", "$2,200", "Kirin 9000 5G", "50MP Ultra-Vision Leica + 12MP 3x + 8MP 10x", "4,400 mAh (66W)", "12GB", "512GB", "Germany", "https://porsche-design.com", "Nano-tech ceramic back with iconic Porsche octagonal camera array and infrared temperature sensor."),
  ("Aston Martin Racing AM788", "$3,500", "Qualcomm Quad-Core", "13MP Main", "3,200 mAh", "3GB", "32GB", "United Kingdom", "https://astonmartin.com", "Bespoke handcrafted handset with carbon-fiber accents and Aston Martin racing team emblems."),
  ("Caviar Gold iPhone 15 Pro", "$10,500", "Apple A17 Pro (3nm)", "48MP Main + 12MP 5x Periscope", "4,422 mAh", "8GB", "1TB", "United States", "https://caviar.global", "Chassis cast in pure 18-karat solid gold with engraved Baroque floral filigree engravings."),
  ("Solana Saga Web3 Phone", "$599", "Snapdragon 8+ Gen 1", "50MP Main + 12MP Wide", "4,110 mAh (33W / Qi)", "12GB LPDDR5", "512GB UFS 3.1", "United States", "https://solanamobile.com", "Dedicated Seed Vault biometric key storage and direct decentralized Web3 dApp store.")
]

for p in phone_extras:
  phones.append(p)

while len(phones) < 100:
  idx = len(phones) + 1
  phones.append((
    f"Flagship Mobile Titan #{idx}",
    f"${max(249, 1199 - (idx * 9))}",
    "Qualcomm Snapdragon 8 Gen 3 (4nm)",
    f"{48 + ((idx * 2) % 60)}MP OIS + 32MP Telephoto + 12MP Ultra-Wide",
    f"{4800 + ((idx * 30) % 800)} mAh (65W Fast Charge)",
    "16GB LPDDR5X",
    "512GB UFS 4.0",
    "United States" if idx % 3 == 0 else "Japan" if idx % 2 == 0 else "South Korea",
    "https://www.gsmarena.com",
    f"Flagship mobile engineered with high-density battery cells, advanced multi-camera optics, and ultra-smooth 120Hz OLED display."
  ))

print(f"Phones total: {len(phones)}")
