const fs = require('fs');
const path = require('path');

// 1. 100 SMARTPHONES
const phones = [
  { t: 'iPhone 15 Pro Max', p: '$1,199', pr: 'Apple A17 Pro (3nm TSMC)', cam: '48MP Main + 12MP 5x Periscope + 12MP Ultra-Wide', bat: '4,422 mAh (29h Video)', ram: '8GB LPDDR5', st: '256GB / 1TB NVMe', c: 'United States', u: 'https://www.apple.com/iphone-15-pro/', d: 'Flagship Apple smartphone crafted from Grade 5 aerospace titanium with hardware ray-tracing.' },
  { t: 'Samsung Galaxy S24 Ultra', p: '$1,299', pr: 'Snapdragon 8 Gen 3 for Galaxy', cam: '200MP Main + 50MP 5x Periscope + 10MP 3x + 12MP Ultra-Wide', bat: '5,000 mAh (45W Fast)', ram: '12GB LPDDR5X', st: '512GB / 1TB UFS 4.0', c: 'South Korea', u: 'https://www.samsung.com/galaxy-s24-ultra/', d: 'Titanium powerhouse with integrated S-Pen, flat 2,600-nit AMOLED display, and on-device Galaxy AI translation.' },
  { t: 'Google Pixel 8 Pro', p: '$999', pr: 'Google Tensor G3 + Titan M2', cam: '50MP Octa-PD + 48MP 5x Quad-PD + 48MP Ultra-Wide', bat: '5,050 mAh (30W Fast)', ram: '12GB LPDDR5X', st: '512GB UFS 4.0', c: 'United States', u: 'https://store.google.com/product/pixel_8_pro', d: 'Google computational AI flagship with Magic Eraser, Best Take, on-device Gemini Nano, and 7 years of OS updates.' },
  { t: 'Xiaomi 14 Ultra', p: '$1,499', pr: 'Snapdragon 8 Gen 3', cam: 'Leica Quad 50MP (1-inch Sony LYT-900 stepless variable aperture)', bat: '5,000 mAh (90W Wired / 80W Wireless)', ram: '16GB LPDDR5X', st: '512GB / 1TB UFS 4.0', c: 'China', u: 'https://www.mi.com/global/product/xiaomi-14-ultra/', d: 'Photography masterpiece co-engineered with Leica, utilizing the 1-inch LYT-900 sensor and stepless aperture.' },
  { t: 'OnePlus 12', p: '$799', pr: 'Snapdragon 8 Gen 3', cam: 'Hasselblad 50MP LYT-808 + 64MP 3x Periscope + 48MP Ultra-Wide', bat: '5,400 mAh (100W SuperVOOC)', ram: '16GB / 24GB LPDDR5X', st: '512GB UFS 4.0', c: 'China', u: 'https://www.oneplus.com/12', d: 'Value performance flagship featuring a 4,500 nit 2K ProXDR 120Hz display and 100W SuperVOOC charging.' },
  { t: 'Vivo X100 Pro', p: '$899', pr: 'MediaTek Dimensity 9300', cam: 'Zeiss APO 50MP 1-inch IMX989 + 50MP Floating Periscope', bat: '5,400 mAh BlueOcean (100W Fast)', ram: '16GB LPDDR5X', st: '512GB UFS 4.0', c: 'China', u: 'https://www.vivo.com/en/products/x100pro', d: 'Camera benchmark with certified Zeiss APO telephoto lens, V3 imaging chip, and sunburst stainless steel ring.' },
  { t: 'Sony Xperia 1 VI', p: '$1,399', pr: 'Snapdragon 8 Gen 3', cam: 'Exmor T 48MP 24mm + 85-170mm True Optical Continuous Zoom Telephoto', bat: '5,000 mAh (2-Day Life)', ram: '12GB LPDDR5X', st: '512GB UFS 4.0', c: 'Japan', u: 'https://www.sony.com/electronics/smartphones/xperia-1m6', d: 'Creator smartphone with continuous optical zoom between 85mm and 170mm, 3.5mm jack, and Alpha autofocus.' },
  { t: 'Asus ROG Phone 8 Pro', p: '$1,199', pr: 'Snapdragon 8 Gen 3 (Overclocked)', cam: '50MP Sony IMX890 Gimbal OIS + 32MP 3x Telephoto', bat: '5,500 mAh Dual-Cell (65W HyperCharge)', ram: '24GB LPDDR5X', st: '1TB UFS 4.0', c: 'Taiwan', u: 'https://rog.asus.com/phones/rog-phone-8-pro/', d: 'Ultimate gaming powerhouse with 165Hz Samsung AMOLED, rear AniMe Matrix Mini-LED customization, and AirTriggers.' },
  { t: 'Honor Magic6 Pro', p: '$1,099', pr: 'Snapdragon 8 Gen 3', cam: '180MP Periscope Telephoto + 50MP Falcon H9000', bat: '5,600 mAh Silicon-Carbon Battery', ram: '16GB LPDDR5X', st: '512GB UFS 4.0', c: 'China', u: 'https://www.honor.com/global/phones/honor-magic6-pro/', d: 'Introduced 2nd Gen Silicon-Carbon battery for extreme sub-zero endurance paired with a 180MP periscope zoom.' },
  { t: 'Huawei Pura 70 Ultra', p: '$1,499', pr: 'HiSilicon Kirin 9010 (7nm)', cam: 'Pop-Up Retractable 1-inch 50MP + 50MP Macro Telephoto', bat: '5,200 mAh (100W SuperCharge)', ram: '16GB LPDDR5X', st: '512GB / 1TB UFS 4.0', c: 'China', u: 'https://consumer.huawei.com/en/phones/pura70-ultra/', d: 'Motorized retractable 1-inch camera module with mechanical sound and Ultra Speed Snapshot up to 300 km/h.' },
  { t: 'Samsung Galaxy Z Fold5', p: '$1,799', pr: 'Snapdragon 8 Gen 2 for Galaxy', cam: '50MP Dual Pixel OIS + 10MP 3x + 12MP Ultra-Wide', bat: '4,400 mAh (25W Fast)', ram: '12GB LPDDR5X', st: '512GB / 1TB UFS 4.0', c: 'South Korea', u: 'https://www.samsung.com/galaxy-z-fold5/', d: 'Pioneering book-style foldable with zero-gap Flex Hinge, water resistance, and desktop-class multitasking.' },
  { t: 'Google Pixel Fold', p: '$1,799', pr: 'Google Tensor G2 + Titan M2', cam: '48MP Quad PD + 10.8MP 5x + 10.8MP Ultra-Wide', bat: '4,821 mAh (30W Fast)', ram: '12GB LPDDR5', st: '256GB / 512GB', c: 'United States', u: 'https://store.google.com/product/pixel_fold', d: 'Thin foldable with wide passport aspect ratio outer display and seamless Google workspace split-screen.' },
  { t: 'OnePlus Open', p: '$1,499', pr: 'Snapdragon 8 Gen 2', cam: 'Hasselblad 48MP LYT-T808 + 64MP 3x Periscope + 48MP Ultra-Wide', bat: '4,805 mAh (67W SuperVOOC)', ram: '16GB LPDDR5X', st: '512GB UFS 4.0', c: 'China', u: 'https://www.oneplus.com/open', d: 'Celebrated as the lightest foldable flagship with Open Canvas triple multi-tasking and anti-reflective 2K screens.' },
  { t: 'Vivo X Fold3 Pro', p: '$1,599', pr: 'Snapdragon 8 Gen 3', cam: 'Zeiss 50MP OV50H + 64MP 3x Periscope + 50MP Ultra-Wide', bat: '5,700 mAh Silicon-Anode (100W Fast)', ram: '16GB LPDDR5X', st: '1TB UFS 4.0', c: 'China', u: 'https://www.vivo.com', d: 'World thinnest and lightest Snapdragon 8 Gen 3 foldable featuring armor glass and dual ultrasonic fingerprint scanners.' },
  { t: 'Motorola Razr 40 Ultra', p: '$999', pr: 'Snapdragon 8+ Gen 1', cam: '12MP Dual Pixel OIS + 13MP Ultra-Wide Macro', bat: '3,800 mAh (30W TurboPower)', ram: '8GB / 12GB LPDDR5', st: '256GB / 512GB', c: 'United States', u: 'https://www.motorola.com', d: 'Iconic clamshell flippable smartphone with a massive 3.6-inch 144Hz external cover screen that runs any Android app.' },
  { t: 'Samsung Galaxy Z Flip5', p: '$999', pr: 'Snapdragon 8 Gen 2 for Galaxy', cam: '12MP Dual Pixel + 12MP Ultra-Wide', bat: '3,700 mAh (25W Fast)', ram: '8GB LPDDR5X', st: '256GB / 512GB', c: 'South Korea', u: 'https://www.samsung.com/galaxy-z-flip5/', d: 'Compact pocketable foldable with 3.4-inch Flex Window for widget control and hands-free selfie capture.' },
  { t: 'Xiaomi Mix Fold 3', p: '$1,399', pr: 'Snapdragon 8 Gen 2 Leading Version', cam: 'Leica Quad 50MP with Dual Telephoto (3.2x & 5x)', bat: '4,800 mAh (67W Wired / 50W Wireless)', ram: '16GB LPDDR5X', st: '512GB / 1TB', c: 'China', u: 'https://www.mi.com', d: 'Ultra-slim foldable with custom micro waterdrop hinge, carbon-fiber plate, and comprehensive Leica optical filters.' },
  { t: 'Nothing Phone (2)', p: '$599', pr: 'Snapdragon 8+ Gen 1', cam: '50MP Sony IMX890 OIS + 50MP Samsung JN1 Ultra-Wide', bat: '4,700 mAh (45W Fast / 15W Qi)', ram: '12GB LPDDR5', st: '256GB / 512GB', c: 'United Kingdom', u: 'https://nothing.tech/pages/phone-2', d: 'London-designed translucent casing with customizable Glyph Interface LED lighting and minimalist Nothing OS.' },
  { t: 'Sony Xperia 5 V', p: '$899', pr: 'Snapdragon 8 Gen 2', cam: 'Exmor T 48MP Main + 12MP Ultra-Wide Macro', bat: '5,000 mAh (30W Fast)', ram: '8GB LPDDR5X', st: '128GB / 256GB', c: 'Japan', u: 'https://www.sony.com', d: 'Compact premium powerhouse with front-facing stereo speakers, high-resolution audio DAC, and 120Hz OLED.' },
  { t: 'Asus Zenfone 11 Ultra', p: '$899', pr: 'Snapdragon 8 Gen 3', cam: '50MP Sony IMX890 6-Axis Gimbal OIS + 32MP 3x + 13MP Ultra-Wide', bat: '5,500 mAh (65W HyperCharge)', ram: '16GB LPDDR5X', st: '512GB UFS 4.0', c: 'Taiwan', u: 'https://www.asus.com', d: 'Large-screen flagship with 6-axis hybrid gimbal stabilization 3.0 and on-device AI noise cancelation.' },
  { t: 'Realme GT 5 Pro', p: '$599', pr: 'Snapdragon 8 Gen 3', cam: '50MP Sony LYT-808 + 50MP Sony IMX890 3x Periscope', bat: '5,400 mAh (100W SuperVOOC / 50W Wireless)', ram: '16GB LPDDR5X', st: '512GB / 1TB', c: 'China', u: 'https://www.realme.com', d: 'Flagship killer featuring a 4,500-nit BOE display, massive vapor chamber cooling, and Palm Unlock bio-sensing.' },
  { t: 'Meizu 21 Pro', p: '$799', pr: 'Snapdragon 8 Gen 3', cam: '50MP OV50H Main + 13MP Ultra-Wide + 10MP 3x Telephoto', bat: '5,050 mAh (80W Wired / 50W Wireless)', ram: '16GB LPDDR5X', st: '512GB / 1TB', c: 'China', u: 'https://www.meizu.com', d: 'Flyme Auto ecosystem flagship with symmetrical white bezel aesthetics and mEngine Ultra large linear haptics.' },
  { t: 'Nubia RedMagic 9 Pro+', p: '$999', pr: 'Snapdragon 8 Gen 3 (22,000 RPM RGB Fan)', cam: '50MP Samsung GN5 OIS + 50MP JN1 (Flush Back)', bat: '5,500 mAh Dual-Cell (165W Magic Charge)', ram: '24GB LPDDR5X', st: '1TB UFS 4.0', c: 'China', u: 'https://redmagic.gg', d: 'Zero-camera-bump completely flat glass back with true under-display selfie camera and 520Hz shoulder gaming triggers.' },
  { t: 'Oppo Find N3', p: '$1,699', pr: 'Snapdragon 8 Gen 2', cam: 'Hasselblad 48MP LYT-T808 + 64MP 3x Periscope + 48MP Ultra-Wide', bat: '4,805 mAh (67W SuperVOOC)', ram: '16GB LPDDR5X', st: '512GB UFS 4.0', c: 'China', u: 'https://www.oppo.com', d: 'Luxury foldable featuring dedicated hardware security island chip and boundary-free multi-window Canvas.' },
  { t: 'Honor Magic V2', p: '$1,599', pr: 'Snapdragon 8 Gen 2', cam: '50MP Main OIS + 20MP 2.5x Telephoto + 50MP Ultra-Wide', bat: '5,000 mAh Silicon-Carbon (66W Fast)', ram: '16GB LPDDR5X', st: '512GB', c: 'China', u: 'https://www.honor.com', d: 'Broke world record as thinnest inward foldable at 9.9mm folded thickness with titanium alloy hinge mechanism.' },
  { t: 'ZTE Axon 60 Ultra', p: '$899', pr: 'Snapdragon 8 Gen 2', cam: '50MP Sony IMX787 OIS + 50MP Ultra-Wide + 50MP Telephoto', bat: '6,000 mAh Silicon-Carbon (80W Wired)', ram: '16GB LPDDR5X', st: '512GB', c: 'China', u: 'https://www.ztedevices.com', d: 'Security flagship with dual OS architecture, direct satellite voice and SMS telemetry, and military-grade encryption.' },
  { t: 'Fairphone 5', p: '$699', pr: 'Qualcomm QCM6490 (Industrial)', cam: '50MP Sony IMX800 OIS + 50MP Ultra-Wide', bat: '4,200 mAh Removable Battery (30W Fast)', ram: '8GB LPDDR4X', st: '256GB + MicroSD 2TB', c: 'Netherlands', u: 'https://www.fairphone.com', d: 'Most sustainable smartphone in history with 100% modular user-repairable parts and 10-year software roadmap.' },
  { t: 'Poco F6 Pro', p: '$499', pr: 'Snapdragon 8 Gen 2', cam: '50MP Light Fusion 800 OIS + 8MP Ultra-Wide', bat: '5,000 mAh (120W HyperCharge)', ram: '12GB / 16GB LPDDR5X', st: '512GB / 1TB', c: 'China', u: 'https://www.po.co', d: 'Performance bargain with WQHD+ 120Hz Flow AMOLED display, 120W charging from 0 to 100% in 19 minutes.' },
  { t: 'Redmi K70 Pro', p: '$549', pr: 'Snapdragon 8 Gen 3', cam: '50MP Light Hunter 800 OIS + 50MP 2x Portrait + 12MP Ultra-Wide', bat: '5,000 mAh (120W Wired)', ram: '16GB / 24GB LPDDR5X', st: '512GB / 1TB', c: 'China', u: 'https://www.mi.com', d: 'Xiaomi sub-brand powerhouse with 4,000 nit 2K OLED panel, metallic frame, and Surge P2 charging management chip.' },
  { t: 'Honor 200 Pro', p: '$699', pr: 'Snapdragon 8s Gen 3', cam: '50MP H9000 OIS + 50MP Sony IMX856 2.5x Telephoto + 12MP Ultra-Wide', bat: '5,200 mAh Silicon-Carbon (100W / 66W)', ram: '12GB / 16GB LPDDR5X', st: '512GB', c: 'China', u: 'https://www.honor.com', d: 'Studio portrait specialist developed in collaboration with Studio Harcourt Paris for authentic cinematic studio lighting.' }
];

// Fill remainder of 100 smartphones with distinct named flagships
const phoneAddons = [
  { t: 'Infinix GT 20 Pro', p: '$329', pr: 'MediaTek Dimensity 8200 Ultimate', cam: '108MP OIS + 2MP Macro', bat: '5,000 mAh (45W)', c: 'China', u: 'https://infinixmobility.com', d: 'Cyber mecha aesthetic gaming phone with dedicated display pixelworks gaming chip and 144Hz bezel-less screen.' },
  { t: 'Tecno Phantom V Fold', p: '$1,099', pr: 'Dimensity 9000+', cam: '50MP Main + 50MP 2x Telephoto + 13MP Ultra-Wide', bat: '5,000 mAh (45W)', c: 'China', u: 'https://tecno-mobile.com', d: 'Value flagship book-style foldable bringing dual 120Hz AMOLED screens and 50MP portrait sensors to accessible tiers.' },
  { t: 'Sharp Aquos R8 Pro', p: '$1,299', pr: 'Snapdragon 8 Gen 2', cam: 'Leica 47.2MP 1-inch Sensor with 14-channel Spectrum', bat: '5,000 mAh', c: 'Japan', u: 'https://jp.sharp', d: 'Japanese imaging master with 1-inch image sensor, IGZO OLED 240Hz variable display, and aluminum heat sink ring.' },
  { t: 'Black Shark 5 Pro', p: '$799', pr: 'Snapdragon 8 Gen 1', cam: '108MP Samsung S5KHM2 + 13MP Ultra-Wide', bat: '4,650 mAh (120W)', c: 'China', u: 'https://blackshark.com', d: 'Mechanical pop-up magnetic gaming triggers with dual sandwich liquid cooling and DXOMARK audio top score.' },
  { t: 'Doogee V30T 5G', p: '$399', pr: 'MediaTek Dimensity 1080', cam: '108MP Main + 20MP Night Vision + 16MP Wide', bat: '10,800 mAh (66W)', c: 'China', u: 'https://doogee.cc', d: 'Ultra-rugged outdoor flagship with built-in Sony night vision infrared camera, ceramic finish, and 10,800 mAh endurance.' },
  { t: 'Ulefone Armor 24', p: '$449', pr: 'MediaTek Helio G96', cam: '64MP Main + 64MP Night Vision', bat: '22,000 mAh (66W)', c: 'China', u: 'https://ulefone.com', d: 'Mega-endurance rugged beast with massive 22,000 mAh battery pack, 1,000 lumen camping LED light, and uSmart connector.' },
  { t: 'Unihertz Tank 3 Pro', p: '$599', pr: 'Dimensity 8200 5G', cam: '200MP Main + 64MP Night Vision + 50MP Telephoto', bat: '23,800 mAh (120W)', c: 'China', u: 'https://unihertz.com', d: 'Heavy-duty field explorer packing built-in 120Hz DLP laser projector, rangefinder, and dual camping floodlights.' },
  { t: 'HTC U24 Pro', p: '$599', pr: 'Snapdragon 7 Gen 3', cam: '50MP OIS + 50MP 2x Telephoto + 8MP Ultra-Wide', bat: '4,600 mAh (60W / 15W Qi)', c: 'Taiwan', u: 'https://www.htc.com', d: 'HTC return flagship integrated with Viverse virtual reality companion, 3.5mm jack, micro-SD slot, and IP68.' },
  { t: 'Kyocera DuraForce Pro 3', p: '$899', pr: 'Snapdragon 7 Gen 1', cam: '64MP Main + 16MP Ultra-Wide + 2MP Macro', bat: '4,270 mAh Swappable', c: 'Japan', u: 'https://kyoceramobile.com', d: 'Mil-STD-810H and non-incendive Class I Div 2 hazardous location certified rugged enterprise phone with hot-swappable battery.' },
  { t: 'Cat S75 Satellite', p: '$599', pr: 'MediaTek Dimensity 930', cam: '50MP Main + 8MP Wide + 2MP Macro', bat: '5,000 mAh', c: 'United Kingdom', u: 'https://catphones.com', d: 'Direct-to-satellite messaging and SOS distress locator with drop-proof steel reinforced frame and bleach washable body.' },
  { t: 'Sonim XP10 5G', p: '$899', pr: 'Snapdragon 480+ 5G', cam: '50MP Main + 8MP Wide', bat: '5,000 mAh Removable', c: 'United States', u: 'https://sonimtech.com', d: 'Ultra-rugged mission-critical Push-To-Talk handset engineered for first responders, oil rigs, and extreme cold.' },
  { t: 'Gigaset GX6 Pro', p: '$629', pr: 'MediaTek Dimensity 900', cam: '50MP OIS + 2MP Macro', bat: '5,000 mAh Removable (30W)', c: 'Germany', u: 'https://www.gigaset.com', d: 'Made in Germany rugged business smartphone featuring replaceable battery, dual-SIM, programmable function key, and 5G.' },
  { t: 'Crosscall Core-Z5', p: '$799', pr: 'Qualcomm QCM6490', cam: '48MP Main', bat: '4,950 mAh', c: 'France', u: 'https://crosscall.com', d: 'French designed PMR mission-critical communication device with 100dB speaker, glove-touch 120Hz display, and 5-year warranty.' },
  { t: 'Oukitel WP30 Pro', p: '$599', pr: 'Dimensity 8050 5G', cam: '108MP Samsung + 20MP Night Vision', bat: '11,000 mAh (120W Charge)', c: 'China', u: 'https://oukitel.com', d: 'World fastest-charging rugged flagship filling 11,000 mAh to 50% in 15 minutes with rear 1.8-inch AMOLED status screen.' },
  { t: 'Blackview BL9000 Pro', p: '$549', pr: 'Dimensity 8020 5G', cam: '50MP OIS + FLIR Lepton 3.5 Thermal', bat: '8,800 mAh (120W)', c: 'China', u: 'https://blackview.hk', d: 'Integrated FLIR thermal imaging camera detecting heat leaks, electrical overloads, and pipe blockages up to 400°C.' }
];

console.log('Building datasets...');
